import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {

    interface CardProps {
        title: string,
        text: string,
        href: string
    }

    function Card(props: CardProps) {
        return (
            <a href={props.href} className="p-6 max-w-sm mx-auto bg-gray-50 rounded-xl shadow-md items-center">
                <div className="text-xl font-medium text-black">{props.title}</div>
                <p className="text-gray-800">{props.text}</p>
            </a>
        );
    }

    return (
        <div className="h-screen w-screen mx-auto grid">
            <Head>
                <title>Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="container mx-auto grid grid-cols-1 content-center">
            <div className="my-10 text-center">
                <h1 className="my-5 text-5xl">
                    Welcome to <a className="text-[gold]" href="https://nextjs.org">Next.js!</a>
                </h1>

                <p className="text-lg">
                    Get started by editing {' '}
                    <code className="code-cell">pages/index.tsx</code>
                </p>
                </div>

                <div className="grid grid-cols-2 gap-5 px-10">
                    <Card
                        title="Documentation &rarr;"
                        text="Find in-depth information about Next.js features and API."
                        href="https://nextjs.org/docs"
                    />

                    <Card
                        title="Learn &rarr;"
                        text="Learn about Next.js in an interactive course with quizzes!"
                        href="https://nextjs.org/learn"
                    />

                    <Card
                        title="Examples &rarr;"
                        text="Discover and deploy boilerplate example Next.js projects."
                        href="https://github.com/vercel/next.js/tree/canary/examples"
                    />

                    <Card
                        title="Deploy &rarr;"
                        text="Instantly deploy your Next.js site to a public URL with Vercel."
                        href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    />
                </div>
            </main>

            <footer className="absolute bottom-0 border-t-2 w-screen p-5 text-right">
                <a
                    href="https://goldmandao.xyz"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Boilerplate by <span className="font-bold">GoldmanDAO<span className="text-[gold]">|</span></span>
                </a>
            </footer>
        </div>
    )
}

export default Home
